// <auto-generated />
namespace JourneyPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addImageToDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addImageToDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201810092026446_addImageToDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
